### ISSUE TITLE
[ISSUE] double apostrophes in menu names

### ISSUE THREAD

**Issue by kerneljake** [AF-1/lms-virtuallibrarycreator#5]
## DESCRIBE THE BUG

Virtual Library names with apostrophes turn into double apostrophes in the GUI (both Material and legacy LMS skin).  For example: `Jake's CDs` turns into `Jake''s CDs`.
<br><br>
## VERSION INFO

Seen in LMS 8.4.0, Virtual Library Creator 1.2.5, Material 4.4.1, Firefox 124.0.2
<br><br>
## SCREENSHOTS

![image](https://github.com/CDrummond/lms-material/assets/6081489/56a3e43d-383d-464b-9f87-11778fd32cd9)

**Comment by AF-1** [comment]
Good catch. That was due to some deprecated code I forgot to remove. v1.2.**6** should fix this.
To update **_existing_** libraries just click _edit_ and then _save_.

**Comment by kerneljake** [comment]
Confirmed fixed in 1.2.6.  Thank you!
