### ISSUE TITLE
[ISSUE] Server version 9.0.0 unable to select multiple Artists

### ISSUE THREAD

**Issue by GeoffClements** [AF-1/lms-virtuallibrarycreator#7]
## BUG DESCRIPTION
Under Create New Virtual Library, option "Only include tracks from selected artists" a drop down with all artists is shown. However, only one artist can be selected from this drop-down.

<br><br>
## EXPECTED BEHAVIOR
I would expect a list of artists that I can select >1 artist. When one artist is selected, no more artists can be selected.

In addition, no menu entry is created to select the virtual library

**Comment by GeoffClements** [comment]
Apologies for the half entry; I got interrupted during the creation of the issue.
Some more information:

Server

Version: 9.0.0 - 1732822968 @ Fri Nov 29 12:08:33 UTC 2024
Hostname: henry
Server IP Address: 192.168.178.2
Operating system: Debian - EN_GB - utf8
Platform Architecture: armv7l-linux
Perl Version: 5.36.0 - arm-linux-gnueabihf-thread-multi-64int
Audio::Scan: 1.10
IO::Socket::SSL: 2.081
Database Version: DBD::SQLite 1.58 (sqlite 3.22.0)

Plugins

Additional Browse Modes 1.0
Don't Stop The Music 1.0.0
Drag & drop music files to play 0.1
Full text search 1.0.0
Material Skin 5.6.0
Music and Artist Information 1.12.2
Online Music Library Integration 1.0
Presets Editor 1.0
Radio 1.0
Random Mix 1.0
Remote Music Libraries 1.0
Report Analytics Data 1.1
Song Scanner 2.0
Sounds & Effects 1.1
Virtual Library Creator 1.3.8

**Comment by GeoffClements** [comment]
After a little investigation I can confirm that this problem is with the Material skin only.

**Comment by AF-1** [comment]
Material has its own way of parsing and displaying html pages (provided by VLC). If you use other skins, you should be able to select (multiple) virtual libraries, artists, composers etc. 
The problem seems to be with html _select_ objects that allow users to select _mutiple_ options. Material has them as single select.
If you ask about this in the Material thread (LMS forum), I'm sure that Craig can fix this.

**Comment by GeoffClements** [comment]
Thanks for your help, have opened an issue on lms-material.

Closing.
